# Generated by Django 3.2.7 on 2021-09-15 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=200)),
                ('room', models.CharField(max_length=200)),
                ('message_body', models.TextField()),
                ('date_sent', models.DateTimeField(auto_now_add=True)),
                ('message_key', models.CharField(max_length=200)),
                ('changed', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('date_sent',),
            },
        ),
    ]
